### ISSUE TITLE
Replace hardcoded username/password combinations with secrets

### ISSUE THREAD

**Issue by darth-veitcher** [darth-veitcher/homelab#7]
Currently the OpenLDAP and Keycloak setups hardcode admin credentials into the manifests. 

Work out how to replace with secrets whilst still maintaining the configmap usage for environment

**Comment by darth-veitcher** [comment]
# Set Secrets
As we're going to have some username/password combinations defined for our authentication services (e.g. database users, root admin users for LDAP and Keycloak etc.) we should store these as `secrets` and then add them into the environment or configuration of the containers in the manifests as references (as opposed to being hardcoded).

There's two options to initially generate and save these secrets. We'll specify to create them only in the `auth` namespace.

## Generic CLI method
```bash tab="Generic CLI"
$ kubectl -n auth create secret generic ldap-user-creds \
      --from-literal=LDAP_ADMIN_PASSWORD=admin \
      --from-literal=LDAP_CONFIG_PASSWORD=config

secret/ldap-user-creds created
```

## Use manifest
We should `base64` encode the secrets first.

```bash
$ echo -n 'admin' | base64

YWRtaW4=

$ echo -n 'config' | base64

Y29uZmln
```

Now use these base64 secrets in the manifest

```yaml
# file: ~/auth/ldap-user-creds-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ldap-user-creds
  namespace: auth
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: YWRtaW4=
  LDAP_CONFIG_PASSWORD: Y29uZmln
```

For either of the above methods for storing the secret you then access the key,value combinations in the deployment manifest like follows:

## Using `envFrom`
```yaml tab="envFrom"
envFrom:
  # Secrets
  - secretRef:
      name: ldap-user-creds
  # Normal plaintext config
  - configMapRef:
      name: ldap-config
```

## Using `env`
```yaml tab="env"
env:
  - name: LDAP_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ldap-user-creds
        key: password
  - name: LDAP_CONFIG_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ldap-user-creds
        key: LDAP_CONFIG_PASSWORD
```
