### ISSUE TITLE
Create path to standard user login

### ISSUE THREAD

**Issue by darth-veitcher** [darth-veitcher/homelab#9]
Could call it `/profile` or something

At the moment hitting auth.jamesveitch.dev will push you to the admin login as opposed to, as a user, being able to login and adjust your profile etc. 

Handle in the ingress

**Comment by darth-veitcher** [comment]
Looks like it probably comes from the `Clients` section

![image](https://user-images.githubusercontent.com/1722315/71403254-166c5580-2627-11ea-992a-edcf784c9f56.png)

**Comment by darth-veitcher** [comment]
Yep, seem to be able to do this with a rewrite rule

```yaml
# Account page
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: keycloak-external-ingress-account
  namespace: auth
  labels:
    app: keycloak
    tier: frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /auth/realms/Development/account/$1
spec:
  tls:
  - hosts:
    - auth.jamesveitch.dev
    secretName: keycloak-certs
  rules:
  - host: auth.jamesveitch.dev
    http:
      paths:
      - path: /account(.*)
        backend:
          serviceName: keycloak
          servicePort: 8080
```
